services:
  - type: web
    name: jelou
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd web && gunicorn -c gunicorn_config.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
